apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: invoicing
  name: invoicing
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: invoicing
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: invoicing
    spec:
      containers:
        - env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
          imagePullPolicy: Always
          image: gcr.io/pl-dev-infra/demos/microservice-kafka/invoicing:1.03
          name: invoicing
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: invoicing
  labels:
    io.kompose.service: invoicing
spec:
  ports:
    - name: client
      port: 8080
      protocol: TCP
  selector:
    io.kompose.service: invoicing
